spring.application.name=RentACar
spring.mvc.servlet.path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/rentacar
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

jwt_configs.secret =  9f3a7c1e4b8d2f6a0c5e9b1d7a3f4c2e
jwt_configs.access_token_validity_s = 3600
jwt_configs.refresh_token_validity_s = 36000

logging.level.root=info
logging.level.org.springframework.security=info

